#!/usr/bin/env bash

podman run --rm \
	-v "${PWD}:/local" \
	openapitools/openapi-generator-cli \
	generate \
	-i https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json \
	-g rust \
	-o /local/out/rust
